#!/bin/bash
echo downloading Task1...
python ./db_admconverter.py Tasks TaskOne
echo downloading Task2...
python ./db_admconverter.py Tasks TaskTwo
echo downloading Task3...
python ./db_admconverter.py Tasks TaskThree
echo downloading Task4...
python ./db_admconverter.py Tasks TaskFour
echo downloading Task5...
python ./db_admconverter.py Graph DisplayGraph

